# Generated by Django 5.2.13 on 2026-05-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profile_photos/'),
        ),
    ]
