# Generated by Django 5.2.13 on 2026-05-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
        ('market', '0002_asset_remove_stockprice_stock_assetprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_threads', to='market.asset'),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debate_sessions', to='market.asset'),
        ),
    ]
