# Generated by Django 5.2.13 on 2026-05-02 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0001_initial'),
        ('market', '0002_asset_remove_stockprice_stock_assetprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestrun',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='market.asset'),
        ),
    ]
