# Generated by Django 5.2.13 on 2026-05-02 16:47

import django.db.models.deletion
from django.db import migrations, models


def copy_stock_data_to_assets(apps, schema_editor):
    Stock = apps.get_model("market", "Stock")
    StockPrice = apps.get_model("market", "StockPrice")
    Asset = apps.get_model("market", "Asset")
    AssetPrice = apps.get_model("market", "AssetPrice")

    for stock in Stock.objects.all():
        Asset.objects.update_or_create(
            id=stock.id,
            defaults={
                "symbol": stock.symbol,
                "name": stock.name,
                "asset_type": "stock",
                "sector": stock.sector,
                "exchange": stock.exchange,
                "currency": stock.currency,
                "is_active": stock.is_active,
                "created_at": stock.created_at,
                "updated_at": stock.updated_at,
            },
        )

    for stock_price in StockPrice.objects.select_related("stock").all():
        AssetPrice.objects.update_or_create(
            id=stock_price.id,
            defaults={
                "asset_id": stock_price.stock_id,
                "date": stock_price.date,
                "open": stock_price.open,
                "high": stock_price.high,
                "low": stock_price.low,
                "close": stock_price.close,
                "adjusted_close": stock_price.adjusted_close,
                "volume": stock_price.volume,
                "source": "legacy",
                "created_at": stock_price.created_at,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('commodity', 'Commodity')], default='stock', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('high', models.DecimalField(decimal_places=6, max_digits=18)),
                ('low', models.DecimalField(decimal_places=6, max_digits=18)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='yahoo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.asset')),
            ],
            options={
                'db_table': 'asset_prices',
                'ordering': ['asset__symbol', 'date'],
            },
        ),
        migrations.RunPython(copy_stock_data_to_assets, noop_reverse),
        migrations.RunSQL(
            sql=(
                "SELECT setval(pg_get_serial_sequence('assets', 'id'), "
                "COALESCE((SELECT MAX(id) FROM assets), 1), "
                "COALESCE((SELECT COUNT(*) FROM assets), 0) > 0);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "SELECT setval(pg_get_serial_sequence('asset_prices', 'id'), "
                "COALESCE((SELECT MAX(id) FROM asset_prices), 1), "
                "COALESCE((SELECT COUNT(*) FROM asset_prices), 0) > 0);"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='stock',
        ),
    ]
