# Generated by Django 5.2.13 on 2026-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtests', '0002_alter_backtestrun_stock'),
        ('conversations', '0002_alter_chatthread_stock_alter_debatesession_stock'),
        ('market', '0002_asset_remove_stockprice_stock_assetprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['asset', 'date'], name='asset_prices_asset_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetprice',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='asset_prices_asset_date_unique'),
        ),
    ]
