# Generated by Django 5.2.14 on 2026-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_add_status_and_rawllm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
