# Generated by Django 5.2.14 on 2026-05-05 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0004_seed_supported_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('base_currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(decimal_places=4, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('average_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_holdings', to='market.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolio_holdings',
                'ordering': ['portfolio__name', 'asset__symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'name'], name='portfolio_user_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='portfolio_user_name_unique'),
        ),
        migrations.AddIndex(
            model_name='portfolioholding',
            index=models.Index(fields=['portfolio', 'asset'], name='pf_hold_port_asset_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='pf_hold_port_asset_uniq'),
        ),
        migrations.AddConstraint(
            model_name='portfolioholding',
            constraint=models.CheckConstraint(condition=models.Q(('target_weight__gte', 0), ('target_weight__lte', 1)), name='pf_hold_weight_range'),
        ),
    ]
